import React, { useState, useMemo } from "react";
import { TrendingUp, TrendingDown, BarChart2 } from "lucide-react";
import { C, MF, FULL_MOS } from "../theme.js";
import { fmt, todayStr } from "../lib/moneyFormat.js";
import { Modal, FI, SH, Empty, iS, ListRow } from "../components/ui.jsx";
import { RechartsReady, ChartPanel, useChartTheme } from "../components/RechartsBridge.jsx";
import { chartValueColor } from "../lib/chartTheme.js";

export default function TradingView({trades,setTrades,account,setAccount,showToast}){
  const ct=useChartTheme();
  const[showAdd,setShowAdd]=useState(false);const[form,setForm]=useState({});const ff=k=>e=>setForm(p=>({...p,[k]:e.target.value}));
  function add(){if(!form.symbol||!form.pnl)return;setTrades(p=>[{id:Date.now(),date:form.date||todayStr(),symbol:form.symbol.toUpperCase(),side:form.side||"Long",contracts:form.contracts||"1",entry:form.entry||"",exit:form.exit||"",pnl:form.pnl,note:form.note||""},...p]);const pnl=parseFloat(form.pnl);showToast&&showToast(`Trade logged — ${form.symbol.toUpperCase()} (${pnl>=0?"+":""}${fmt(pnl)})`);setForm({});setShowAdd(false);}
  const totalPnl=trades.reduce((s,t)=>s+(parseFloat(t.pnl)||0),0);const wins=trades.filter(t=>parseFloat(t.pnl)>0);const losses=trades.filter(t=>parseFloat(t.pnl)<0);
  const winRate=trades.length>0?((wins.length/trades.length)*100).toFixed(0):0;const avgWin=wins.length>0?wins.reduce((s,t)=>s+(parseFloat(t.pnl)||0),0)/wins.length:0;const avgLoss=losses.length>0?Math.abs(losses.reduce((s,t)=>s+(parseFloat(t.pnl)||0),0)/losses.length):0;
  const bal=parseFloat(account.balance||0),dep=parseFloat(account.deposit||0),ret=dep>0?((bal-dep)/dep*100).toFixed(1):0;
  const monthly=trades.reduce((a,t)=>{const m=t.date?FULL_MOS[new Date(t.date).getMonth()].slice(0,3):"?";a[m]=(a[m]||0)+(parseFloat(t.pnl)||0);return a},{});
  const chartData=Object.entries(monthly).map(([month,pnl])=>({month,pnl}));
  const equityData=useMemo(()=>{let run=parseFloat(account.deposit||0);return[...trades].sort((a,b)=>a.date?.localeCompare(b.date)).map((t,i)=>{run+=(parseFloat(t.pnl)||0);return{i:i+1,equity:parseFloat(run.toFixed(2)),pnl:parseFloat(t.pnl)||0};});},[trades,account.deposit]);
  const eqUp=equityData.length?equityData[equityData.length-1]?.equity>=(parseFloat(account.deposit||0)):true;
  const eqColor=eqUp?C.positive:C.negative;
  return(<div className="fu fv-view-root">
    <SH title="Futures Trading" sub="P&L, win rate & performance" onAdd={()=>setShowAdd(true)} addLabel="Log Trade"/>
    <div className="fv-hero-panel" style={{marginBottom:14}}>
      <div className="fv-stat-label" style={{color:"rgba(255,255,255,.55)",marginBottom:4}}>Trading account</div>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:18}}><div><div style={{fontFamily:MF,fontSize:30,fontWeight:800,color:"#fff",lineHeight:1}}>{fmt(bal)}</div><div style={{fontSize:13,color:"rgba(255,255,255,.5)",marginTop:4}}>Current balance</div></div><div style={{textAlign:"right"}}><div style={{fontFamily:MF,fontSize:20,fontWeight:700,color:totalPnl>=0?C.positiveMid:C.negativeMid}}>{totalPnl>=0?"+":""}{fmt(totalPnl)}</div><div style={{fontSize:12,color:"rgba(255,255,255,.4)"}}>Total P&L</div></div></div>
      <div style={{display:"flex",gap:4}}>{[["Deposited",fmt(dep)],["Return",ret+"%"],["Trades",String(trades.length)]].map(([l,v])=><div key={l} style={{flex:1,background:"rgba(255,255,255,.08)",borderRadius:10,padding:"9px 10px"}}><div style={{fontSize:10,color:"rgba(255,255,255,.4)",fontWeight:600,marginBottom:2}}>{l}</div><div style={{fontFamily:MF,fontSize:14,fontWeight:700,color:"#fff"}}>{v}</div></div>)}</div>
    </div>
    <div className="fv-card" style={{padding:16,marginBottom:14}}><div style={{fontSize:12,fontWeight:600,color:C.slate,marginBottom:10}}>Update balances</div><div style={{display:"flex",gap:10,marginBottom:10}}><div style={{flex:1}}><div style={{fontSize:11,color:C.textLight,marginBottom:4}}>Total deposited</div><input type="number" placeholder="0.00" value={account.deposit||""} onChange={e=>setAccount(p=>({...p,deposit:e.target.value}))} onBlur={e=>{if(e.target.value)showToast("Deposit saved");}} style={{...iS(false),padding:"9px 12px",fontSize:13}}/></div><div style={{flex:1}}><div style={{fontSize:11,color:C.textLight,marginBottom:4}}>Current balance</div><input type="number" placeholder="0.00" value={account.balance||""} onChange={e=>setAccount(p=>({...p,balance:e.target.value}))} onBlur={e=>{if(e.target.value)showToast("Balance saved");}} style={{...iS(false),padding:"9px 12px",fontSize:13}}/></div></div><div style={{display:"flex",justifyContent:"center"}}><div style={{fontSize:11,color:C.positive,fontWeight:600,display:"flex",alignItems:"center",gap:5}}><div style={{width:6,height:6,borderRadius:"50%",background:C.positive}}/>Changes save automatically</div></div></div>
    <div className="fv-grid-2" style={{marginBottom:14}}>{[{l:"Win rate",v:winRate+"%",c:parseFloat(winRate)>=50?C.positive:C.negative},{l:"Profit factor",v:avgLoss>0?(avgWin/avgLoss).toFixed(2):"∞",c:C.accent},{l:"Avg win",v:fmt(avgWin),c:C.positive},{l:"Avg loss",v:"-"+fmt(avgLoss),c:C.negative}].map(s=><div key={s.l} className="fv-card" style={{padding:14}}><div style={{fontSize:11,fontWeight:600,color:C.slate,textTransform:"uppercase",letterSpacing:.4,marginBottom:4}}>{s.l}</div><div style={{fontFamily:MF,fontSize:22,fontWeight:800,color:s.c}}>{s.v}</div></div>)}</div>
    {chartData.length>0&&<ChartPanel title="Monthly P&L" subtitle="By calendar month"><RechartsReady minHeight={160} render={R=>(<R.ResponsiveContainer width="100%" height={160}><R.BarChart data={chartData} margin={ct.margin}><R.CartesianGrid stroke={ct.gridStroke} strokeDasharray="3 3" vertical={false}/><R.XAxis dataKey="month" tick={ct.axisTick} axisLine={false} tickLine={false}/><R.YAxis tick={ct.axisTick} axisLine={false} tickLine={false} tickFormatter={ct.formatYAxis}/><R.Tooltip contentStyle={ct.tooltipStyle} formatter={v=>[fmt(v),"P&L"]}/><R.Bar dataKey="pnl" radius={ct.barRadius}>{chartData.map((d,i)=><R.Cell key={i} fill={chartValueColor(d.pnl)}/>)}</R.Bar></R.BarChart></R.ResponsiveContainer>)}/></ChartPanel>}
    {equityData.length>1&&<ChartPanel title="Equity curve" subtitle="Cumulative account value per trade"><RechartsReady minHeight={160} render={R=>(<R.ResponsiveContainer width="100%" height={160}><R.AreaChart data={equityData} margin={ct.margin}><defs><linearGradient id="eqGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={eqColor} stopOpacity={.2}/><stop offset="100%" stopColor={eqColor} stopOpacity={0}/></linearGradient></defs><R.CartesianGrid stroke={ct.gridStroke} strokeDasharray="3 3" vertical={false}/><R.XAxis dataKey="i" tick={ct.axisTickSm} axisLine={false} tickLine={false}/><R.YAxis tick={ct.axisTickSm} axisLine={false} tickLine={false} tickFormatter={ct.formatYAxis} width={50}/><R.Tooltip formatter={(v,n)=>n==="equity"?[fmt(v),"Account value"]:[fmt(v),"Trade P&L"]} contentStyle={ct.tooltipStyle}/><R.Area type="monotone" dataKey="equity" name="equity" stroke={eqColor} strokeWidth={ct.areaStrokeWidth} fill="url(#eqGrad)" dot={false}/></R.AreaChart></R.ResponsiveContainer>)}/></ChartPanel>}
    <div className="fv-page-title" style={{marginBottom:10}}>Trade log</div>
    {trades.length===0&&<Empty text="No trades yet. Tap Log Trade to start." icon={BarChart2}/>}
    {trades.map(t=>{const pnl=parseFloat(t.pnl)||0;const up=pnl>=0;return(<ListRow key={t.id} icon={up?<TrendingUp size={18} color={C.positive}/>:<TrendingDown size={18} color={C.negative}/>} title={t.symbol} sub={`${t.date} · ${t.side} · ${t.contracts} contract${t.contracts!=="1"?"s":""}${t.note?" · "+t.note:""}`} right={(up?"+":"")+fmt(pnl)} rightColor={up?C.positive:C.negative} rightSub={t.entry&&t.exit?t.entry+" – "+t.exit:""} onDelete={()=>{setTrades(p=>p.filter(x=>x.id!==t.id));showToast&&showToast("Trade removed","error");}} badge={up?{label:"WIN",bg:C.greenBg,color:C.positive}:{label:"LOSS",bg:C.redBg,color:C.negative}}/>);})}
    {showAdd&&<Modal title="Log Trade" icon={BarChart2} onClose={()=>setShowAdd(false)} onSubmit={add} submitLabel="Log Trade" wide><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><FI half label="Symbol" placeholder="ES, NQ, CL..." value={form.symbol||""} onChange={ff("symbol")}/><FI half label="Date" type="date" value={form.date||todayStr()} onChange={ff("date")}/></div><div style={{display:"flex",gap:10,marginBottom:14}}>{["Long","Short"].map(s=><button key={s} type="button" className="ba" onClick={()=>setForm(p=>({...p,side:s}))} style={{flex:1,padding:"10px",borderRadius:10,border:`1.5px solid ${form.side===s?C.accent:C.border}`,background:form.side===s?C.accentBg:C.surface,color:form.side===s?C.accent:C.textMid,fontWeight:700,fontSize:13,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",gap:6}}>{s==="Long"?<TrendingUp size={14}/>:<TrendingDown size={14}/>}{s}</button>)}</div><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><FI half label="Contracts" type="number" placeholder="1" value={form.contracts||""} onChange={ff("contracts")}/><FI half label="P&L ($)" type="number" placeholder="+250 or -150" value={form.pnl||""} onChange={ff("pnl")}/></div><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><FI half label="Entry price" type="number" value={form.entry||""} onChange={ff("entry")}/><FI half label="Exit price" type="number" value={form.exit||""} onChange={ff("exit")}/></div><FI label="Note" placeholder="Setup, lesson..." value={form.note||""} onChange={ff("note")}/></Modal>}
  </div>);
}
